const SET_LOADING = "SET_LOADING";
const LOAD_CART = "LOAD_CART";
const CLEAR_CART = "CLEAR_CART";
const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";
const REMOVE_ITEM = "REMOVE_ITEM";
const COUNT_TOTAL = "COUNT_TOTAL";

export {
  SET_LOADING,
  LOAD_CART,
  CLEAR_CART,
  INCREASE_ITEM_COUNT,
  DECREASE_ITEM_COUNT,
  REMOVE_ITEM,
  COUNT_TOTAL,
};
