const SET_LOADING = "SET_LOADING";
const LOAD_CART = "LOAD_CART";
const CLEAR_CART = "CLEAR_CART";
const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";

export {
  SET_LOADING,
  LOAD_CART,
  CLEAR_CART,
  INCREASE_ITEM_COUNT,
  DECREASE_ITEM_COUNT,
};
